source 'https://cdn.cocoapods.org/'
platform :ios, '17.0'

# 상위 PopPang-RN 프로젝트의 node_modules를 사용한다.
require_relative '../node_modules/react-native/scripts/react_native_pods'

# React Native Core와 의존성의 prebuilt 사용 여부는 실행 스크립트가 결정한다.
# build_xcframeworks.sh는 source-build를, New_build_xcframeworks.sh는 prebuilt를 요청한다.
# 값을 지정하지 않으면 React Native 0.86의 기본값인 prebuilt를 사용한다.

inhibit_all_warnings!

prepare_react_native_project!

# Podfile은 react_native_prebuild 안에 있지만,
# 자동 연결 대상은 상위 PopPang-RN/package.json이다.
root_autolink_command = [
  'node',
  '-e',
  "process.chdir('..'); process.argv = ['', '', 'config']; require('@react-native-community/cli').run()"
]

target 'ReactNativePrebuild' do
  use_frameworks! :linkage => :static

  # 루트 package.json에 있는 iOS 네이티브 RN 모듈을 자동으로 Pods에 추가한다.
  config = use_native_modules!(root_autolink_command)

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
